### ISSUE TITLE
ViewLatestTestResults

### ISSUE THREAD

**Issue by kthomp576** [KeesV/kv-vsts-ViewLatestTestResult#1]
we recently installed this plugin for TFS and we are not seeing what I would expect based on your details and screenshots. Should we see this show on the test case tabs when we go to view the test case steps? it should display with the steps, summary, links, etc.?

Would this display on user stories and tasks as well, but return an error on that tab?

**Comment by KeesV** [comment]
Are you using VSTS or an on-premise TFS installation?

**Comment by kthomp576** [comment]
On Premise.

Thank you,

Kevin Thompson
Manager, Digital Quality Assurance
http://www.hsn.comhttp://www.hsn.com/
HSN, 1 HSN Drive, St. Petersburg, FL 33729
Office 727.872.5647
kevin.thompson@hsn.netmailto:kevin.thompson@hsn.net

**Comment by mbendtsen** [comment]
Was this ever resolved? I have the same issue. I have customized the Test Case WIT. 
Strange that this feature is not a part of TFS.

**Comment by aanthony8** [comment]
I am having the same issue with TFS On-Premise, has there been a solution?

**Comment by KeesV** [comment]
Latest version should work with TFS on-premise.
