### ISSUE TITLE
Not able to see the Test Results tab on Test Case work Item in Migrated VSTS Account.

### ISSUE THREAD

**Issue by sriramdasbalaji** [KeesV/kv-vsts-ViewLatestTestResult#2]
Hi,

I have installed the Test Results extension in my VSTS account(Migrated account). But I am not able to see the Test Results tab in Test case work item form. It is working fine in another VSTS account which is not migrated one. Please let us know how we can make it work on migrated VSTS account.

Thanks 
Sriramdas Balaji

**Comment by KeesV** [comment]
With the latest version, I think you should be able to make it work by following the instructions for TFS on-premise.
