### ISSUE TITLE
Only one test result showing up in test results control

### ISSUE THREAD

**Issue by abbottbd** [KeesV/kv-vsts-ViewLatestTestResult#4]
We've installed this extension on prem but we don't see what the screen shot shows.  WHen we open a test case that has hundreds of results, the 'test results' tab only shows 1 single result - not the entire history or list of results.

**Comment by KeesV** [comment]
Hi Brian,
What you noticed is the exact intended behavior of the extension :-). The extension is designed to show the latest test result for each test plan / test suite / configuration combination for which it is included. So you won't see any result history. That might be a nice addition for the future.
